### ISSUE TITLE
Very upsetting

### ISSUE THREAD

**Issue by yedef77482** [cjsaylor/chessbot#46]
![Screenshot 2019-10-29 at 12 14 03](https://user-images.githubusercontent.com/57140856/67770579-8e1a6b80-fa4e-11e9-89bc-5ad1f5e7c092.png)

**Comment by cjsaylor** [comment]
@yedef77482 It is looking for a promotion as part of the move. See https://www.chris-saylor.com/chessbot/gameplay/moves.html#piece-promotion.

I am planning to improve the feedback of the invalid moves to be more specific about what is the issue of the move.
