### ISSUE TITLE
@chessbot e1c1 results in "chess: invalid move e1c1"

### ISSUE THREAD

**Issue by lruminski** [cjsaylor/chessbot#65]
I can't seem to castle queenside in a game.

![image](https://user-images.githubusercontent.com/19661/103372977-9d0d0b80-4aa1-11eb-88cc-ad3a9c1c5e0b.png)

the game was in this thread https://drawmeclose.slack.com/archives/C01GJRLD0BW/p1607385649001400

**Comment by cjsaylor** [comment]
@lruminski Hi Luke.

`e1c1` is actually not a valid move according to the rules of castling:

> Castling is permissible provided all of the following conditions hold:
> * The castling must be kingside or queenside.
> * Neither the king nor the chosen rook has previously moved.
> * There are no pieces between the king and the chosen rook.
> * The king is not currently in check.
> * **_The king does not pass through a square that is attacked by an enemy piece._**
> * The king does not end up in check. (True of any legal move.)

The emphasized rule is what would make this invalid. The black queen puts the king in check on `d1`.

See 3.8.2 of the FIDE rule set for reference: https://handbook.fide.com/chapter/E012018
