### ISSUE TITLE
chessbot.chris-saylor.com is down

### ISSUE THREAD

**Issue by Rwwn** [cjsaylor/chessbot#78]
Hi

Chessbot stopped responding to our commands in Slack a few days ago, so I tried removing it and re-adding it to the workspace to see if that would fix it, but when I do that I'm confronted with a Cloudflare error page:
![image](https://github.com/cjsaylor/chessbot/assets/46853149/6059175c-e216-4a01-a159-cebca620cce2)

Seems the server chessbot runs on is down, which is a shame, it's been very fun to use. Is there any chance it can be restored?

Cheers

**Comment by cjsaylor** [comment]
@Rwwn Sorry I missed this message. It was down for a few days when I was doing a server move and had a misconfiguration, however it has been up and running since.
